name: bmi_calculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^0.1.14

flutter:
  uses-material-design: true

msix_config:
  display_name: BMI Calculator
  publisher_display_name: Carlos Carvalho
  # identity_name: MyCompany.MySuite.MyApp
  msix_version: 1.0.0.0
  # certificate_path: C:\<PathToCertificate>\<MyCertificate.pfx>
  # certificate_password: 1234 (require if using .pfx certificate)
  # publisher: CN=My Company, O=My Company, L=Berlin, S=Berlin, C=DE
  # logo_path: C:\<PathToIcon>\<Logo.png>
  # start_menu_icon_path: C:\<PathToIcon>\<Icon.png>
  # tile_icon_path: C:\<PathToIcon>\<Icon.png>
  # vs_generated_images_folder_path: C:\<PathToFolder>\Images
  # icons_background_color: transparent (or some color like: '#ffffff')
  architecture: x64
  # capabilities: 'internetClient,location,microphone,webcam'
